config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :orders
      resources :menus
      resources :categories
      get "/reports" => "reports#index"
      post "/reports/email" => "reports#show_by_email"
      post "/reports/total-price" => "reports#show_by_range_total_price"
      post "/reports/range-date" => "reports#show_by_range_date"
    end
  end 

  get "/" => "orders#index"
  get "/reports" => "reports#index"
  post "/reports/email" => "reports#show_by_email"
  post "/reports/total-price" => "reports#show_by_range_total_price"
  post "/reports/range-date" => "reports#show_by_range_date"
  
  resources :orders
  resources :menus
  resources :categories
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Login deactivated because can't implemented in RSpec
  # get "login" => "users#index"
  # post "login" => "users#login"
  # post "logout" => "users#logout"

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :category_details
  has_many :order_details
  has_many :categories, through: :category_details 
  has_many :orders, through: :order_details
  
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, comparison: { greater_than: 0.01 }, numericality: true
  validates :description, presence: true, length: { maximum: 150 }
end

app/controllers/api/v1/menus_controller.rb
class Api::V1::MenusController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_menu, only: %i[ show edit update destroy ]

  def index
    @menus = Menu.all
    render json: @menus
  end

  def show
    @categories = @menu.categories
    render json: @menu, status: 201
  end

  def create
    @menu = Menu.new(menu_params)
    @categories = params[:category_id]
    
    if !@categories.nil? && @menu.save
      @categories.each do |category|
        #Add each categories of new menu to category details
        @category_details = CategoryDetail.new(
          menu_id: @menu.id,
          category_id: category
        )
        @category_details.save
      end

      render json: @menu, status: 201
    else
      render json: @menu.errors, status: 422
    end
  end

  def update    
    if @menu.update(menu_params)
      render json: @menu, status: 201
    else
      render json: @menu.errors, status: 422
    end
  end

  def destroy
    CategoryDetail.destroy_by(menu_id: @menu.id)
    @menu.destroy
    render :json => {:success => true}
  end

  private
    # Use callbacks to share current category between actions for show/update/delete.
    def set_menu
      @menu = Menu.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def menu_params
      params.permit(:name, :price, :description)
    end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]
  # before_action :authenticate_user
  # Login deactivated because error implemented in RSpec
  
  def index
    @menus = Menu.all
  end

  def show
    @categories = @menu.categories
  end

  def new
    @menu = Menu.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
  end

  def create
    @menu = Menu.new(menu_params)
    @categories = params[:category_id]
    
    if !@categories.nil? && @menu.save
      @categories.each do |category|
        #Add each categories of new menu to category details
        @category_details = CategoryDetail.new(
          menu_id: @menu.id,
          category_id: category
        )
        @category_details.save
      end
      flash[:notice] = "Menu was successfully created."
      redirect_to menu_url(@menu)
    else
      redirect_to("/menus/new", status: 302)
    end
  end

  def update    
    if @menu.update(menu_params)
      flash[:notice] = "Menu was successfully updated."
      redirect_to menu_url(@menu)
    else
      edit_menu_path(@menu, status: 302)
    end
  end

  def destroy
    CategoryDetail.destroy_by(menu_id: @menu.id)
    @menu.destroy
    flash[:notice] = "Menu was successfully destroyed."
    redirect_to menus_url
  end

  private
    # Use callbacks to share current category between actions for show/update/delete.
    def set_menu
      @menu = Menu.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def menu_params
      params.permit(:name, :price, :description)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<div>
  <p>Name:</p>
  <input type="text" name="name" value="<%= @menu.name %>" placeholder="Name">
</div>
  
<div>
  <p>Price:</p>
  <input type="number" name="price" value="<%= @menu.price %>" placeholder="Price">
</div>

<div>
  <p>Description:</p>
  <textarea name="description" placeholder="Description"><%= @menu.description %></textarea>
</div>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p>
    <strong>Name:</strong>
    <%= menu.name %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= menu.price %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= menu.description %>
  </p>
</div>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= form_tag(@menu, {method: :put}) do %>
  <%= render "form", menu: @menu %>
  <input type="submit" value="Update Menu">
<% end %>

<br>
  
<div>
  <%= link_to "Show this menu", @menu %> |
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>List of Menu</h1>

<div id="menus">
  <table style="width: 75%; text-align: left;">
    <thead>
      <th>No</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th></th>
    </thead>
    <tbody>
      <% @menus.each_with_index do |menu, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= menu.name %></td>
          <td><%= menu.price %></td>
          <td><%= menu.description %></td>
          <td><%= link_to "Show this menu", menu %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New menu", new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= form_tag("/menus", {method: :post}) do %>
  <%= render "form", menu: @menu %>
    
  <div>
    <p>Category:</p>
    <% @categories.each do |category| %>
      <input type="checkbox" name="category_id[]" value="<%= category.id %>">
      <label><%= category.name %></label>
    <% end %>
  </div>
      
  <input type="submit" value="Create a Menu">
<% end %>

<br>

<div>
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu %>

<p>
  <strong>Category:</strong>
  <% @categories.each do |category| %>
    <%= category.name %>,
  <% end %>
</p>

<div>
  <%= link_to "Edit this menu", edit_menu_path(@menu) %> |
  <%= link_to "Back to menu", menus_path %>

  <%= button_to "Destroy this menu", @menu, method: :delete %>
</div>