config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :orders
      resources :menus
      resources :categories
      get "/reports" => "reports#index"
      post "/reports/email" => "reports#show_by_email"
      post "/reports/total-price" => "reports#show_by_range_total_price"
      post "/reports/range-date" => "reports#show_by_range_date"
    end
  end 

  get "/" => "orders#index"
  get "/reports" => "reports#index"
  post "/reports/email" => "reports#show_by_email"
  post "/reports/total-price" => "reports#show_by_range_total_price"
  post "/reports/range-date" => "reports#show_by_range_date"
  
  resources :orders
  resources :menus
  resources :categories
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Login deactivated because can't implemented in RSpec
  # get "login" => "users#index"
  # post "login" => "users#login"
  # post "logout" => "users#logout"

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :menus, through: :order_details
  
  validates :customer_email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :total, presence: true
  validates :status, presence: true, inclusion: { in: %w(NEW PAID CANCELED), message: "is not a valid status" }
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_order, only: %i[ show edit update destroy ]
  
  def index
    @orders = Order.all
    render json: @orders
  end

  def show
    @menus = @order.menus
    render json: @order, status: 201
  end

  def create
    @email = params[:customer_email]
    @menus = params[:menu_id]
    @quantity = params[:quantity]
    @total = 0
  
    if !@menus.nil? && !@quantity.empty? && !@email.empty?
      @order = Order.new(
        customer_email: @email,
        total: calculate_total_order(@menus, @quantity),
        status: "NEW"
      )

      if @order.save
        @menus.each_with_index do |menu, index|
          @menu_price = Menu.find_by(id: menu).price
          
          OrderDetail.new(
            order_id: @order.id,
            menu_id: menu,
            menu_price: @menu_price,
            quantity: @quantity[index],
            sub_total: @menu_price * @quantity[index].to_f
          ).save
        end
        
        render json: @order, status: 201
      else 
        render json: @order.errors, status: 422
      end
    end
  end

  def update
    if @order.update(order_params)
      render json: @order, status: 201
    end
  end
  
  def destroy
    OrderDetail.destroy_by(order_id: @order.id)
    @order.destroy
    render :json => {:success => true}
  end
  
  private
    # Use callbacks to share current category between actions for show/update/delete.
    def set_order
      @order = Order.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def order_params
      params.permit(:customer_email, :status)
    end

    # Use to calculate total price of order
    def calculate_total_order(menus, quantities)
      total_order = 0
      
      menus.each_with_index do |menu, index|
        menu_price = Menu.find_by(id: menu).price
        subtotal = menu_price * quantities[index].to_f
        total_order += subtotal
      end
      return total_order
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  # before_action :authenticate_user
  # Login deactivated because error implemented in RSpec
  
  def index
    @orders = Order.all
  end

  def show
    @menus = @order.menus
  end

  def new
    @order = Order.new
    @menus = Menu.all
  end

  def edit
  end

  def create
    @email = params[:customer_email]
    @menus = params[:menu_id]
    @quantity = params[:quantity].compact_blank
    @total = 0
  
    if !@menus.nil? && !@quantity.empty? && !@email.empty?
      @order = Order.new(
        customer_email: @email,
        total: calculate_total_order(@menus, @quantity),
        status: "NEW"
      )

      if @order.save
        @menus.each_with_index do |menu, index|
          @menu_price = Menu.find_by(id: menu).price
          
          OrderDetail.new(
            order_id: @order.id,
            menu_id: menu,
            menu_price: @menu_price,
            quantity: @quantity[index],
            sub_total: @menu_price * @quantity[index].to_f
          ).save
        end
        
        flash[:notice] = "Order was successfully created."
        redirect_to order_url(@order)
      end
    else
      redirect_to("/orders/new", status: 302)
    end
  end

  def update    
    if @order.update(order_params)
      flash[:notice] = "Order was successfully updated."
      redirect_to order_url(@order)
    end
  end

  def destroy
    OrderDetail.destroy_by(order_id: @order.id)
    @order.destroy
    flash[:notice] = "Order was successfully destroyed."
    redirect_to orders_url
  end

  private
    # Use callbacks to share current category between actions for show/update/delete.
    def set_order
      @order = Order.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def order_params
      params.permit(:customer_email, :status)
    end

    # Use to calculate total price of order
    def calculate_total_order(menus, quantities)
      total_order = 0
      menus.each_with_index do |menu, index|
        menu_price = Menu.find_by(id: menu).price
        subtotal = menu_price * quantities[index].to_f
        total_order += subtotal
      end
      return total_order
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<h1>Editing Menu</h1>

<%= form_tag(@order, {method: :patch}) do %>
  <table>
    <tr>
      <td><label for="customer_email">Customer Email</label></td>
      <td>:</td>
      <td><input type="text" name="customer_email" placeholder="Customer Email" value="<%= @order.customer_email %>"></td>
    </tr>
    <tr>
      <td><label>Status</label></td>
      <td>:</td>
      <td>
        <select name="status">
          <option value="NEW" 
            <% if @order.status.eql? "NEW" %>
              selected
            <% end %>>
              NEW
            </option>
          <option value="PAID"
            <% if @order.status.eql? "PAID" %>
              selected
            <% end %>>
              PAID
            </option>
          <option value="CANCELED"
            <% if @order.status.eql? "CANCELED" %>
              selected
            <% end %>>
              CANCELED
            </option>
        </select>
      </td>
    </tr>
  </table>
  <input type="submit" value="Edit Order">
<% end %>

<br>
  
<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>List of Order</h1>

<div id="orders">
  <table style="width: 50%; text-align: left;">
    <thead>
      <th>No</th>
      <th>Order Date</th>
      <th>Customer Email</th>
      <th>Total</th>
      <th>Status</th>
      <th></th>
    </thead>
    <tbody>
      <% @orders.each_with_index do |order, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= order.created_at %></td>
          <td><%= order.customer_email %></td>
          <td><%= order.total %></td>
          <td><%= order.status %></td>
          <td><%= link_to "Show this order", order %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_tag("/orders", {method: :post}) do %>
  <div>
    <label for="customer_email">Customer Email:</label>
    <input type="text" name="customer_email" placeholder="Customer Email">
  </div>
  <div>
    <p>Menu:</p>
    <table>
      <tbody>
        <% @menus.each do |menu| %>
          <tr>
            <td><input type="checkbox" name="menu_id[]" value="<%= menu.id %>"></td>
            <td><label><%= menu.name %></label></td>
            <td><input type="number" name="quantity[]" placeholder="Quantity"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <input type="submit" value="Create a Order">
<% end %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<table>
  <tbody>
    <tr>
      <td><b>Customer Email</b></td>
      <td><b>:</b></td>
      <td><b><%= @order.customer_email %></b></td>
    </tr>
    <tr>
      <td><b>Order Date</b></td>
      <td><b>:</b></td>
      <td><b><%= @order.created_at %></b></td>
    </tr>
    <tr>
      <td><b>Status</b></td>
      <td><b>:</b></td>
      <td><b><%= @order.status %></b></td>
    </tr>
  </tbody>
</table>

<br>

<table style="width: 40%; text-align: center;">
  <thead>
    <th>No</th>
    <th>Menu</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Sub total</th>
  </thead>
  <tbody>
    <% @menus.each_with_index do |menu, index| %>
      <% @order_detail = OrderDetail.find_by(order_id: @order.id, menu_id: menu.id) %>
        <tr>
          <td style="text-align: center;"><%= index + 1 %></td>
          <td><%= menu.name %></td>
          <td><%= @order_detail.menu_price %></td>
          <td style="text-align: center;"><%= @order_detail.quantity %></td>
          <td><%= @order_detail.sub_total %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <tbody>
    <tr>
      <td><b>Total</b></td>
      <td><b>:</b></td>
      <td><b><%= @order.total %></b></td>
    </tr>
  </tbody>
</table>
      
<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to order", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>